services:
  db:
    image: postgres:17.3
    environment:
      POSTGRES_DB: school_management
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    image: school_management:v1
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: school_management
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
      CELERY_BROKER_URL: "amqp://user:password@rabbitmq:5672/"
      CELERY_RESULT_BACKEND: "rpc://"
      ELASTICSEARCH_HOST: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: changeme
  
  worker:
    image: school_management:v1
    command: ["celery", "-A", "school_management", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: school_management
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
      CELERY_BROKER_URL: "amqp://user:password@rabbitmq:5672/"
      CELERY_RESULT_BACKEND: "rpc://"
      ELASTICSEARCH_HOST: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: changeme

  rabbitmq:
    image: "rabbitmq:4.0.6-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    environment:
      discovery.type: single-node
      xpack.security.transport.ssl.enabled: false
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: changeme
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  postgres_data:
