# Generated by Django 5.1.6 on 2025-02-13 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='base.studentgroup'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardians',
            field=models.ManyToManyField(related_name='students', through='base.GuardianStudent', to='base.guardian'),
        ),
    ]
